### ISSUE TITLE
Constraint Detection add on could not start

### ISSUE THREAD

**Issue by ChrisChinSeeq** [HAW-Process-Automation/Constraint-Detection#3]
Hi,

I am raising this support ticket on behalf of SBMOffshore who completed the Constraint Detection add on installation but could not start. SBMOffshore is using Seeq R60.2. Attached here the screenshot of error message.

Please get in touch with SBMOffshore Seeq admin focal point is: Chenxiang, Pan <Pan.Chenxiang@sbmoffshore.com> and copy me at Christopher.chin@seeq.com 

Thank you.

Best regards,
Christopher Chin
Seeq Analytics Engineer
![image-20230523-081119](https://github.com/HAW-Process-Automation/Constraint-Detection/assets/123725851/82d79a21-fa43-44bd-9b03-f7146264458a)

**Comment by anvenkat18** [comment]
I think this is fixed in 0.0.41. Please upgrade and try.
